---
title: "Ponds_metanetwork"
author: "Carine Emer and Decio Correa"
date: "03/09/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(bipartite)
library (networkD3)
library(reshape)
library(reshape2)
library(igraph)
library(magrittr)

library(readr)

```

```{r input data}

setwd("~/Dropbox/Decio metanetwork/Ponds_metanetwork")
 #setwd("D:/Carine/Decio metanetwork/Ponds_metanetwork")

load("~/Dropbox/Decio metanetwork/Ponds_metanetwork/ponds.Rdata")

dcnf<-read.csv("dcnf_spp.csv", header=TRUE, row.names = 1)
ebb<-read.csv("ebb_spp.csv", header=TRUE, row.names = 1)
ecolab<-read.csv("ecolab_spp.csv", header=TRUE, row.names = 1)

## txt
ecolab <- read.table("ECOLAB_pond_X_interaction_species_tad_bac.txt", head=TRUE)
dcnf <- read.table("DCNF_pond_X_interaction_species_tad_bac.txt", head=TRUE)
ebb <- read.table("EBB_pond_X_interaction_species_tad_bac.txt", head=TRUE)


## edgelists
#ecolab_edl<-read.csv("ecolab_edgelist.csv", header=TRUE)



```


```{r checking data}

rowSums(ebb)
#   Bomba    Brejo  Castelo Pedreira       R2       R3 
#       0     1209      988      690        0        0 
rowSums(ecolab)
# C1   D1   D2   L1   L2   LS   SW 
# 982 1179  487  354  241  321  703 
rowSums(dcnf)
#pond18_1  pond19_1  pond29_1  pond29_2  pond29_4  pond36_1     pond8 pondSFA_2 
 #       0      1072       458       662       558       315         0       279 
#pondSFA_4 
    #  382 

str(ecolab_edl)


```

degree, k= number of interactions each pond has (lower) or number of ponds in which each interaction occurs (higher)

betweenness = connectors
```{r centrality}

###### dcnf
k_dcnf<-specieslevel(dcnf, index="degree",level="higher") ## interaction degree
write.csv(k_dcnf,"degree dcnf.csv")
btw_dcnf<-specieslevel(dcnf, index="betweenness",level="higher")
write.csv(btw_dcnf,"btw dcnf.csv")

k_dcnf_lower<-specieslevel(dcnf, index="degree",level="lower") ## ponds' degree
write.csv(k_dcnf_lower,"degree lower dcnf.csv")
btw_dcnf_lower<-specieslevel(dcnf, index="betweenness",level="lower")
write.csv(btw_dcnf_lower,"btw lower dcnf.csv")

###### ebb

k_ebb<-specieslevel(ebb, index="degree",level="higher")
write.csv(k_ebb,"degree ebb.csv")
btw_ebb<-specieslevel(ebb, index="betweenness",level="higher")
write.csv(btw_ebb,"btw ebb.csv")

k_ebb_lower<-specieslevel(ebb, index="degree",level="lower")
write.csv(k_ebb_lower,"degree lower ebb.csv")
btw_ebb_lower<-specieslevel(ebb, index="betweenness",level="lower")
write.csv(btw_ebb_lower,"btw lower ebb.csv")


##### ecolab

k_ecolab<-specieslevel(ecolab, index="degree",level="higher")
write.csv(k_ecolab,"degree ecolab.csv")
btw_ecolab<-specieslevel(ecolab, index="betweenness",level="higher")
write.csv(btw_ecolab,"btw ecolab.csv")

k_ecolab_lower<-specieslevel(ecolab, index="degree",level="lower")
write.csv(k_ecolab_lower,"degree lower ecolab.csv")
btw_ecolab_lower<-specieslevel(ecolab, index="betweenness",level="lower")
write.csv(btw_ecolab_lower,"btw lower ecolab.csv")




```


```{r modularity}

##### Modularity using Beckett 2016' algorithm - faster and more stable
mod_ebb<-computeModules(ebb)
mod_ebb

########### testing modularity significance with null models
#### check the method to use, it varies quite a bit, and can give different results. The choice of the model depends on the question, but to avoid problems, I usually run quite a few of them and check if the results are consistent or not. We can disscuss this later as well.

nulls <- nullmodel(mod_ebb, N=1, method=3) ## check the method to use, it varies quite a bit, and can give different results. We can disscuss this later as well.
modules.nulls <- sapply(nulls, computeModules)
like.nulls <- sapply(modules.nulls, function(x) x@likelihood)
z <- (mod_ebb@likelihood - mean(like.nulls))/sd(like.nulls) ## if mod_ebb@likelihood doesnt work, replace by the value of 'mod_ebb'
p <- 2*pnorm(-abs(z))


plot(density(modules.nulls), lwd=2, xlim=c(0, 20))
abline(v=mod_ebb, col="red", lwd=2)

```

```{r nestedness}

### Estimate nestendss for qualitative and quantitative data. Again, change method accordingly, but the best algorithm is always any variation of the "NODF".
nested_ebb<-nested(ebb, method = "NODF2", rescale = TRUE) ## when running by frequency/quantitative data, use NODF2 that re-order the data from more to less interactions, otherwise NODF

### null model
#### there are quite a few parameters that can be changed here. Lets start with this, a play with changes later if we feel like it.
obs <- nested_ebb

null <-nullmodel(ebb, N=1000, method=5, rep.cell=FALSE) ## method 5 mgen for binary networks - number of interactions and links constant 
null1 <-sapply (X=null, FUN=nested, method="NODF") ## sapply to aplly the NODF for each random netw
means_null1 <- apply (X=cbind(null1),MARGIN=2, FUN=mean, na.rm=T)  #cbind=para colocar os dados em linhas e colunas # Margin = a coluna que quer fazer o cálculo
sd.means_null1 <- apply(X=cbind(null1), MARGIN=2, FUN=sd, na.rm=T)
z_ebb<-(obs-means_null1)/sd.means_null1
z_ebb
sum(null1>= obs)/1000 # valor de p

plot(density(null1), lwd=2, xlim=c(0, 20))
abline(v=obs, col="red", lwd=2)
```



```{r graph networks}

###### DCNF
dcnf_m<-as.matrix(dcnf)
data1<-melt(dcnf_m) ## transform to edgelist
dim(data)
data <- subset(data1, value==1) ## select only interactions =1
write.csv(data,"dcnf_edgelist.csv")
g=graph.data.frame(data,directed=FALSE) # sets the graph framework

####  SIMPLE  NETWORK
simpleNetwork(data)


### OR
# Find group membership
wt <- cluster_walktrap(g, steps = 16)
members <- membership(wt)
# Convert igraph to list for networkD3
sj_list <- igraph_to_networkD3(g, group = members)

# Plot as a forceDirected Network
ntw<-forceNetwork(Links = sj_list$links, Nodes = sj_list$nodes, Source = 'source',
          Target = 'target', NodeID = 'name', Group = 'group',
              zoom = TRUE, linkDistance = 50,opacity=1.2)
 ,          colourScale = "d3.scale.category20f()")
saveNetwork(ntw, 'ntw_ecolab.html', selfcontained =T)



############### EBB
ebb_m<-as.matrix(ebb)
data1<-melt(ebb_m) ## transform to edgelist
data <- subset(data1, value==1) ## select only interactions =1
#write.csv(data,"ebb_edgelist.csv")
g=graph.data.frame(data,directed=FALSE) # sets the graph framework

# Find group membership
wt <- cluster_walktrap(g, steps = 16)
members <- membership(wt)
# Convert igraph to list for networkD3
 sj_list <- igraph_to_networkD3(g, group = members)
# Plot as a forceDirected Network
 ebb_ntw<-forceNetwork(Links = sj_list$links, Nodes = sj_list$nodes, Source = 'source',
          Target = 'target', NodeID = 'name', Group = 'group',
              zoom = TRUE, linkDistance = 50,opacity=1.2)
 ,          colourScale = "d3.scale.category20f()")
saveNetwork(ebb_ntw, 'ntw_ebb.html', selfcontained =T)

############ ECOLAB

ecolab_m<-as.matrix(ecolab)
data1<-melt(ecolab_m) ## transform to edgelist
data <- subset(data1, value==1) ## select only interactions =1
write.csv(data,"ecolab_edgelist.csv")
#data<-ecolab_edl
g=graph.data.frame(data,directed=FALSE) # sets the graph framework

# Find group membership
wt <- cluster_walktrap(g, steps = 16)
members <- membership(wt)
 # Convert igraph to list for networkD3
 sj_list <- igraph_to_networkD3(g, group = members)
# Plot as a forceDirected Network
 ecolab_ntw<-forceNetwork(Links = sj_list$links, Nodes = sj_list$nodes, Source = 'source',
          Target = 'target', NodeID = 'name', Group = 'group',
              zoom = TRUE, linkDistance = 50,opacity=1.2)
           colourScale = "d3.scale.category20f()")

saveNetwork(ecolab_ntw, 'ntw_ecolab.html', selfcontained =T)

save.image("ponds.RData")

```

